# _config.yml
title: Leonella's Vacation Home
description: "Your perfect escape in a beautiful, quiet residential area. Enjoy comfort, privacy, and convenience just minutes from essential amenities and major routes."
